export default {
  1: [
    "Legionnaire",
    "Praetorian",
    "Imperian",
    "Equites Legati",
    "Equites Imperatoris",
    "Equites Caesaris",
    "Battering ram",
    "Fire Catapult",
    "Senator",
    "Settler",
  ],
  2: [
    "Clubswinger",
    "Spearman",
    "Axeman",
    "Scout",
    "Paladin",
    "Teutonic Knight",
    "Ram",
    "Catapult",
    "Chief Settler",
    "Settler",
  ],
  3: [
    "Phalanx",
    "Swordsman",
    "Pathfinder",
    "Theutates Thunder",
    "Druidrider",
    "Haeduan",
    "Ram",
    "Trebuchet",
    "Chieftain",
    "Settler",
  ],
  4: ["Rat", "Spider", "Snake", "Bat", "Wild Boar", "Wolf", "Bear", "Crocodile", "Tiger", "Elephant"],
};
